# Configuração do H2 (modo file):
spring.datasource.url=jdbc:h2:file:./data/readings
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto do Hibernate:
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console:
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do JPA:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor:
server.port=8080

